#!/usr/bin/perl -w
use strict;
use Socket;
my ($remote,$port, $iaddr, $paddr, $proto, $local);

$local = `hostname -s`;
chomp($local);
$remote  = shift || 'localhost';
$port    = shift || 2345;  # random port
if ($port =~ /\D/) { $port = getservbyname($port, 'tcp') }
die "No port" unless $port;
$iaddr   = inet_aton($remote)               || die "no host: $remote";
$paddr   = sockaddr_in($port, $iaddr);

$proto   = getprotobyname('tcp');
socket(SOCK, PF_INET, SOCK_STREAM, $proto)  || die "socket: $!";
print "$local(",
	join(".", unpack("C4", scalar(gethostbyname($local)))),
	")  -->  $remote(",
	join(".", unpack("C4", scalar(gethostbyname($remote)))),
	")  Port: $port  Status: ";
if (connect(SOCK, $paddr))
	{
	print "Open\n";
	}
else
	{
	print "Closed\n";
	}
close (SOCK);
exit;

